### PR TITLE
Fix: Workflows

### PR DESCRIPTION
**Pull request by Yash-sudo-web**

### CODE REVIEW

**Comment by Yash-sudo-web** [comment]
Issue #89 
Workflows are working now but there are a lot of test cases that are failing

**Comment by Delta456** [comment]
Hi @Yash-sudo-web! Thanks for the PR. You have done the first part well. That is very awesome! 

You also need to fix the tests as listed in the issue. After that we will review your PR.

**Comment by harsha509** [comment]
Hi @Yash-sudo-web,

Thank you for the PR.

The CI failures are due to the key issues in workflow. Will fix and rerun the actions again!

**Comment by harsha509** [comment]
Approving as,
* This is a good fix that fixes the build startup failure due to `esbuild`. ref https://github.com/LambdaTest/wdio-lambdatest-service/actions/runs/11117053635/job/30888357977

* Tests are working fine locally as CI needs Secret key update.

**Review by harsha509 — APPROVED** [review]
Thank you @Yash-sudo-web !

**Pull request merged**
